update arch (#47)
* create node project

* configure serverless

* cria pasta src

* env: serverless configuration

* env: serverless configuration

* configure for local

* [ENV] GithubActions serverless-workflow.yml (#2)

* Create serverless-workflow.yml

* env: serverless configuration

* fix: remove serverless framework

* Update aws-workflow.yml

* Update aws-workflow.yml

* env: api gateway and lambda dev env

* add cors

* remove serverless action

* env: configure cors

* fix: Access-Control-Allow-Headers

* fix: remove old infra

* fix: cors headers config

* env: configure api

* fix: configs

* fix: configs

* fix: configs

* change mesasge

* [ENV] Dev 2 AWS (#7)

* env: serverless configuration

* env: serverless configuration

* [ENV] GithubActions serverless-workflow.yml (#2)

* Create serverless-workflow.yml

* env: serverless configuration

* fix: remove serverless framework

* Update aws-workflow.yml

* Update aws-workflow.yml

* env: api gateway and lambda dev env

* env: configure cors

* fix: Access-Control-Allow-Headers

* fix: remove old infra

* fix: cors headers config

* env: configure api

* fix: configs

* fix: configs

* fix: configs

* env: configure new lambda

Co-authored-by: cavalodeaco <96729577+cavalodeaco@users.noreply.github.com>

* [ENV] Fix src path (#8)

* env: serverless configuration

* env: serverless configuration

* [ENV] GithubActions serverless-workflow.yml (#2)

* Create serverless-workflow.yml

* env: serverless configuration

* fix: remove serverless framework

* Update aws-workflow.yml

* Update aws-workflow.yml

* env: api gateway and lambda dev env

* env: configure cors

* fix: Access-Control-Allow-Headers

* fix: remove old infra

* fix: cors headers config

* env: configure api

* fix: configs

* fix: configs

* fix: configs

* env: configure new lambda

* fix: path to src based on container

Co-authored-by: cavalodeaco <96729577+cavalodeaco@users.noreply.github.com>

* Dev 2 aws (#9)

* env: serverless configuration

* env: serverless configuration

* [ENV] GithubActions serverless-workflow.yml (#2)

* Create serverless-workflow.yml

* env: serverless configuration

* fix: remove serverless framework

* Update aws-workflow.yml

* Update aws-workflow.yml

* env: api gateway and lambda dev env

* env: configure cors

* fix: Access-Control-Allow-Headers

* fix: remove old infra

* fix: cors headers config

* env: configure api

* fix: configs

* fix: configs

* fix: configs

* env: configure new lambda

* fix: path to src based on container

* fix: path to src based on container

Co-authored-by: cavalodeaco <96729577+cavalodeaco@users.noreply.github.com>

* install cors

* hello from server

* remove path server

* Dev 2 aws (#10)

* env: serverless configuration

* env: serverless configuration

* [ENV] GithubActions serverless-workflow.yml (#2)

* Create serverless-workflow.yml

* env: serverless configuration

* fix: remove serverless framework

* Update aws-workflow.yml

* Update aws-workflow.yml

* env: api gateway and lambda dev env

* env: configure cors

* fix: Access-Control-Allow-Headers

* fix: remove old infra

* fix: cors headers config

* env: configure api

* fix: configs

* fix: configs

* fix: configs

* env: configure new lambda

* fix: path to src based on container

* fix: path to src based on container

* env: configure infra

Co-authored-by: cavalodeaco <96729577+cavalodeaco@users.noreply.github.com>

* add status endpoint

* env: add production config

* env: fix workflow name

* fix: prod name

* fix: description

* configure local development

* env: change method for status API

* env: add dynamodb into development

* dynamoose hello world

* add local docker to gitignore

* change user id to string

* use ppv table

* chore: update readme

* fix: folders

* fix: folders

* fix: structure

- update folders
- fix import modules
- testing local

* fix: block action on drafts

* fix: module import

* fix: remove docker_volume

* feat: add env TABLE_NAME to lambda

* fix: table to dev and prod and rescue

* fix: action on PR

* fix: adding if to block on draft PR

* fix: infra path to code

* fix: server file

* fix: codeuri path

* fix: change file name

* feat: adding user model

* feat: validate json data

* feat: update user model structure

* feat: add schema do dynamoose

* fix: user model

* fix: remove enroll

* fix: remove enroll

* fix: remove enroll

* feat: enroll

* feat: response

* fix: var to let

* fix: validate enroll and imports

* fix: import table

* feat: update fields

* fix: terms

* Create codeql-analysis.yml (#20)

* Update aws-production.yml (#22)

* driver licence uf

* feat: configure cognito

* feat: cognito (#26)

* fix: name

* fix: remove from gateway

* feat: none auth

* test: lambda auth

* test: auth none

* test: auth

* test: required

* restore serverless-dev.yml

* Cognito (#29)

* feat: cognito

* test: add testing folder

* Update aws-development.yml

* Update aws-development.yml

* Cognito (#30)

* feat: cognito

* test: add testing folder

* Cognito (#31)

* feat: cognito

* test: add testing folder

* fix: remove cognito from output

* Cognito (#32)

* feat: cognito

* test: add testing folder

* fix: remove cognito from output

* fix: remove authentication

* config prod (#33)

* feat: cognito

* test: add testing folder

* fix: remove cognito from output

* fix: remove authentication

* feat: update aws prod with cognito

* Update serverless-prd.yml

* feat: allow loggin with user and password

* fix: list

* fix: list

* fix: yml

* fix: yml

* fix: yml

* fix: yml

* fix: yml

* test: change python version

* fix: rollback

* Revert to 9be382c

* feat: allow login

* feat: add errors

* feat: adding report with validation of token

* fix: adding env variables

* fix: remove reserved variable name

* fix: remove reserved variable name

* fix: remove reserved variable name

* fix: remove reserved variable name

* fix: change validate to middleware

* feat: solves #38"

* fix: remove throws

* fix: optimization

* fix: move error

* fix: remove else

* fix: remove import

* fix: suggestions and generate secret to client app

* feat: getting client secret;

* fix: roolback according to #41

* fix: disable generate secret

* fix: delete file

* feat: update production and remove client_secret

* feat: report endpoint + change token location

* fix: param

* fix: token validation

* fix: order

* fix: TypeError: callback is not a function

* feat: report + dynamo via aws

* feat: api to get report

* feat: add ignore to dynamodblocal

* fix: remove files

* fix: ignore

* feat: fix issues + new APIs

* feat: using token

* fix: message and status

* fix: remove return

* fix: validate json

* fix: errors

* fix: dynamo confs

* fix: change pk name

* feat: change to dynamodb table template

* fix: user data

* feat: enable produciton with new dynamo template

* fix: strucute and routes

* fix: middleware jwt ok

* fix: route login

* fix: serverless init file

* feat: update arch

---------

Co-authored-by: Gian Maurício Fritsche <gianmauriciofritsche@MacBook-Air-de-Gian.local>
Co-authored-by: Giovanna G B Fritsche <ggarciabas@gmail.com>